### PR TITLE
wrap shell arguments in double quotes

### PR DESCRIPTION
**Pull request by shlomif**
see: https://github.com/rohanrhu/gdb-frontend/pull/29

### CODE REVIEW

**Comment by rohanrhu** [comment]
Hi, thank you for the commit. What is the purpose of wrapping these?

**Comment by shlomif** [comment]
Hi @rohanrhu !

> Hi, thank you for the commit. What is the purpose of wrapping these?

See https://shlomif-tech.livejournal.com/14671.html . It handles inner whitespace better.

**Comment by rohanrhu** [comment]
Yes but `$PYCMD` is just `python` or `python3` 🙂

Thank you for your commit. 🎉

**Comment by shlomif** [comment]
On Fri, 10 Sep 2021 16:54:32 -0700
Oğuzhan Eroğlu ***@***.***> wrote:

> Yes but `$PYCMD` is just `python` or `python3` 🙂
> 
> Thank you for your commit. 🎉
> 

You're welcome. Thanks for merging this PR!

-- 

Shlomi Fish       https://www.shlomifish.org/
What Makes Software Apps High Quality -  https://shlom.in/sw-quality

Chuck Norris does not own a dishwasher. His dishes know better than to become
dirty.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Pull request merged**
